name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v3
    - name: install js test libs from npm
      run: npm install
    - name: Build
      run: cargo build
    - name: curl moz_central
      run: curl https://hg.mozilla.org/mozilla-central/archive/tip.zip/js/src/jit-test/tests/ --output moz-central.zip
    - name: unzip moz-central
      run: unzip -qq moz-central.zip -d moz-central
    - name: Run tests
      run: cargo test --release --features=moz_central
      env:
        RUST_MIN_STACK: 9999999
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      env: 
        RUST_MIN_STACK: 9999999
      with: 
        args: --features=moz_central
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: Check syntax
      run: cargo fmt --all -- --check
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}.node_modules
    - name: before cargo cache
      run: rm -rf ~/.cargo/registry
    - name: Cache cargo directory
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}.cargo
        path: ~/.cargo
